# -*- coding: utf-8 -*-
"""message_parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tFhSwtzU5g1BxzKLWt5njGr_5ePyZbOn
"""

import re

pattern = r'\b([Nn]ext|[Ll]ast|[Aa]fter|[Ee]very|[Tt]oday|[Tt]omorrow|[Nn]oon|[Mm]onday|[Tt]uesday|[Ww]ednesday|[Tt]hursday|[Ff]riday|[Ss]aturday|[Ss]unday|[Jj]anuary|[Ff]ebruary|[Mm]arch|[Aa]pril|[Jj]une|[Jj]uly|[Aa]ugust|[Ss]eptember|[Oo]ctober|[Nn]ovember|[Dd]ecember|[Jj]an|[Ff]eb|[Mm]arch|[Aa]pr|[Mm]ay|[Jj]un|[Jj]ul|[Aa]ug|[Ss]ep|[Oo]ct|[Nn]ov|[Dd]ec|[Yy]ear|[Mm]onth|[Ww]eek|[Aa][mM]|[Pp][Mm]|[Aa]t|[Oo]n|[Bb]y|[Ff]rom|to|[Bb]efore|[Aa]fter|between|[Dd]uring|[Ii]n|[Nn]ext|[Aa]fternoon|[Mm]orning|[Nn]oon|[Ee]vening|[Mm]idnight|(?:[0-1]?[0-9]|2[0-3]):[0-5][0-9]|[0-9]+)\b'

text = input("Input your SMS to confirm the meeting time:   ")

matches = re.findall(pattern, text)

underscored_text = text
for match in matches:
  underscored_text = re.sub(r'\b'+ re.escape(match)+r'\b', f'_{match}_', underscored_text)
underscored_text = re.sub(r'_, _', ',_ _', underscored_text)
final_text = re.sub(r'_ _', ' ', underscored_text)
print(final_text)

